### ISSUE TITLE
how spring-stomp headers handle  ":"

### ISSUE THREAD

**Issue by ZMHING** [spring-guides/gs-messaging-stomp-websocket#61]
i put dateTime(for example: 2020-03-20 13:56:57) into spring-stomp headers, but the client display this:
![image](https://user-images.githubusercontent.com/37565801/77140007-0bed1b00-6ab3-11ea-815f-63eae403359b.png)

":" is converted to "\c", why?

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. Also you'll likely need to provide more details for anyone to be able to help you.
